version: '3.3'

volumes:
  db-data:
  db:
    driver: local
  redis_data:

services:
  api:
    image: backend
    container_name: api
    build:
      context: .
    command: npm run start
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

  migrate:
    image: backend
    container_name: migrate
    build:
      context: .
    command: npm run db:migrate
    ports:
      - 3001:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  eth-crawler:
    image: backend
    container_name: eth-crawler
    build:
      context: .
    command: npm run eth-crawl-tx
    ports:
      - 3002:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  polygon-crawler:
    image: backend
    container_name: polygon-crawler
    build:
      context: .
    command: npm run polygon-crawl-tx
    ports:
      - 3003:3000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    container_name: pg_container
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_DB: cosplay-token-transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5446:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
