version: '3.3'

volumes:
  db-data:
  db:
    driver: local

services:
  api:
    image: backend-nest
    container_name: api_test
    build:
      context: .
    command: npm run start
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    container_name: pg_container_test
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_DB: nest-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5447:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
